name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Unzip project
        run: |
          unzip soc-portfolio.zip -d .
      - name: Install dependencies
        run: |
          cd soc-portfolio
          npm install
      - name: Build and Export
        run: |
          cd soc-portfolio
          npm run build
          npm run export
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: soc-portfolio/out
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
